version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 4001 -b '0.0.0.0'
    container_name: recipe_09_api_web
    volumes:
      - .:/recipe_09_api
    ports:
      - "4001:4001"
    depends_on:
      - db

volumes:
  db_data: {}
