default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_0900_ai_ci
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  port: 3306

development:
  <<: *default
  database: recipe_09_dev
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

test:
  <<: *default
  database: recipe_09_test
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

# production:
#   <<: *default
#   database: recipe_09_prod
#   username: recipe-09-db-user

local:
  <<: *default
  database: recipe_09_prod
  username: recipe-09-db-user
  password: <%= ENV["CLOUD_SQL_DB_PASSWORD"] %>
  host: 127.0.0.1
